Update armv7hl/exynos config file: CONFIG_DRM_PTN3460=y
DRM_EXYNOS_DP depends on DRM_PTN3460, and we have the former built-in,
so the latter must be built-in as well. Otherwise we get a linker
failure like:

.../linux-3.15-rc5/drivers/gpu/drm/exynos/exynos_dp_core.c:1004:
undefined reference to `ptn3460_init'