- Linux 6.6.37 (bsc#1218260).
- iio: pressure: fix some word spelling errors (bsc#1218260).
- iio: pressure: bmp280: Fix BMP580 temperature reading
  (bsc#1218260).
- usb: typec: ucsi: Never send a lone connector change ack
  (bsc#1218260).
- usb: typec: ucsi: Ack also failed Get Error commands
  (bsc#1218260).
- Input: ili210x - fix ili251x_read_touch_data() return value
  (bsc#1218260).
- pinctrl: fix deadlock in create_pinctrl() when handling
  -EPROBE_DEFER (bsc#1218260).
- pinctrl: rockchip: fix pinmux bits for RK3328 GPIO2-B pins
  (bsc#1218260).
- pinctrl: rockchip: fix pinmux bits for RK3328 GPIO3-B pins
  (bsc#1218260).
- pinctrl: rockchip: use dedicated pinctrl type for RK3328
  (bsc#1218260).
- pinctrl: rockchip: fix pinmux reset in rockchip_pmx_set
  (bsc#1218260).
- MIPS: pci: lantiq: restore reset gpio polarity (bsc#1218260).
- selftests: mptcp: print_test out of verify_listener_events
  (bsc#1218260).
- selftests: mptcp: userspace_pm: fixed subtest names
  (bsc#1218260).
- wifi: mac80211: Use flexible array in struct ieee80211_tim_ie
  (bsc#1218260).
- ASoC: rockchip: i2s-tdm: Fix trcm mode by setting clock on
  right mclk (bsc#1218260).
- ASoC: mediatek: mt8183-da7219-max98357: Fix kcontrol name
  collision (bsc#1218260).
- ASoC: atmel: convert not to use asoc_xxx() (bsc#1218260).
- ASoC: atmel: atmel-classd: Re-add dai_link->platform to fix
  card init (bsc#1218260).
- workqueue: Increase worker desc's length to 32 (bsc#1218260).
- ASoC: q6apm-lpass-dai: close graph on prepare errors
  (bsc#1218260).
- bpf: Add missed var_off setting in set_sext32_default_val()
  (bsc#1218260).
- bpf: Add missed var_off setting in coerce_subreg_to_size_sx()
  (bsc#1218260).
- s390/pci: Add missing virt_to_phys() for directed DIBV
  (bsc#1218260).
- ASoC: amd: acp: add a null check for chip_pdev structure
  (bsc#1218260).
- ASoC: amd: acp: remove i2s configuration check in
  acp_i2s_probe() (bsc#1218260).
- ASoC: fsl-asoc-card: set priv->pdev before using it
  (bsc#1218260).
- net: dsa: microchip: fix initial port flush problem
  (bsc#1218260).
- openvswitch: get related ct labels from its master if it is
  not confirmed (bsc#1218260).
- mlxsw: spectrum_buffers: Fix memory corruptions on Spectrum-4
  systems (bsc#1218260).
- bpf: Fix overrunning reservations in ringbuf (bsc#1218260).
- ibmvnic: Free any outstanding tx skbs during scrq reset
  (bsc#1218260).
- net: phy: micrel: add Microchip KSZ 9477 to the device table
  (bsc#1218260).
- net: dsa: microchip: use collision based back pressure mode
  (bsc#1218260).
- ice: Rebuild TC queues on VSI queue reconfiguration
  (bsc#1218260).
- xdp: Remove WARN() from __xdp_reg_mem_model() (bsc#1218260).
- netfilter: fix undefined reference to 'netfilter_lwtunnel_*'
  when CONFIG_SYSCTL=n (bsc#1218260).
- btrfs: use NOFS context when getting inodes during logging
  and log replay (bsc#1218260).
- Fix race for duplicate reqsk on identical SYN (bsc#1218260).
- ALSA: seq: Fix missing channel at encoding RPN/NRPN MIDI2
  messages (bsc#1218260).
- net: dsa: microchip: fix wrong register write when masking
  interrupt (bsc#1218260).
- sparc: fix old compat_sys_select() (bsc#1218260).
- sparc: fix compat recv/recvfrom syscalls (bsc#1218260).
- parisc: use correct compat recv/recvfrom syscalls (bsc#1218260).
- powerpc: restore some missing spu syscalls (bsc#1218260).
- tcp: fix tcp_rcv_fastopen_synack() to enter TCP_CA_Loss for
  failed TFO (bsc#1218260).
- ALSA: seq: Fix missing MSB in MIDI2 SPP conversion
  (bsc#1218260).
- netfilter: nf_tables: fully validate NFT_DATA_VALUE on store
  to data registers (bsc#1218260).
- net: mana: Fix possible double free in error handling path
  (bsc#1218260).
- bpf: Take return from set_memory_ro() into account with
  bpf_prog_lock_ro() (bsc#1218260).
- powerpc/bpf: rename powerpc64_jit_data to powerpc_jit_data
  (bsc#1218260).
- powerpc/bpf: use bpf_jit_binary_pack_[alloc|finalize|free]
  (bsc#1218260).
- bpf: Take return from set_memory_rox() into account with
  bpf_jit_binary_lock_ro() (bsc#1218260).
- drm/panel: ilitek-ili9881c: Fix warning with GPIO controllers
  that sleep (bsc#1218260).
- vduse: validate block features only with block devices
  (bsc#1218260).
- vduse: Temporarily fail if control queue feature requested
  (bsc#1218260).
- x86/fpu: Fix AMD X86_BUG_FXSAVE_LEAK fixup (bsc#1218260).
- mtd: partitions: redboot: Added conversion of operands to a
  larger type (bsc#1218260).
- wifi: ieee80211: check for NULL in ieee80211_mle_size_ok()
  (bsc#1218260).
- bpf: Mark bpf prog stack with kmsan_unposion_memory in
  interpreter mode (bsc#1218260).
- RDMA/restrack: Fix potential invalid address access
  (bsc#1218260).
- net/iucv: Avoid explicit cpumask var allocation on stack
  (bsc#1218260).
- net/dpaa2: Avoid explicit cpumask var allocation on stack
  (bsc#1218260).
- crypto: ecdh - explicitly zeroize private_key (bsc#1218260).
- ALSA: emux: improve patch ioctl data validation (bsc#1218260).
- media: dvbdev: Initialize sbuf (bsc#1218260).
- irqchip/loongson: Select GENERIC_IRQ_EFFECTIVE_AFF_MASK if
  SMP for IRQ_LOONGARCH_CPU (bsc#1218260).
- soc: ti: wkup_m3_ipc: Send NULL dummy message instead of
  pointer message (bsc#1218260).
- gfs2: Fix NULL pointer dereference in gfs2_log_flush
  (bsc#1218260).
- drm/radeon/radeon_display: Decrease the size of allocated memory
  (bsc#1218260).
- nvme: fixup comment for nvme RDMA Provider Type (bsc#1218260).
- drm/panel: simple: Add missing display timing flags for KOE
  TX26D202VM0BWA (bsc#1218260).
- gpio: davinci: Validate the obtained number of IRQs
  (bsc#1218260).
- RISC-V: fix vector insn load/store width mask (bsc#1218260).
- drm/amdgpu: Fix pci state save during mode-1 reset
  (bsc#1218260).
- riscv: stacktrace: convert arch_stack_walk() to noinstr
  (bsc#1218260).
- gpiolib: cdev: Disallow reconfiguration without direction
  (uAPI v1) (bsc#1218260).
- randomize_kstack: Remove non-functional per-arch entropy
  filtering (bsc#1218260).
- x86: stop playing stack games in profile_pc() (bsc#1218260).
- parisc: use generic sys_fanotify_mark implementation
  (bsc#1218260).
- Revert "MIPS: pci: lantiq: restore reset gpio polarity"
  (bsc#1218260).
- pinctrl: qcom: spmi-gpio: drop broken pm8008 support
  (bsc#1218260).
- ocfs2: fix DIO failure due to insufficient transaction credits
  (bsc#1218260).
- nfs: drop the incorrect assertion in nfs_swap_rw()
  (bsc#1218260).
- mm: fix incorrect vbq reference in purge_fragmented_block
  (bsc#1218260).
- mmc: sdhci-pci-o2micro: Convert PCIBIOS_* return codes to errnos
  (bsc#1218260).
- mmc: sdhci-brcmstb: check R1_STATUS for erase/trim/discard
  (bsc#1218260).
- mmc: sdhci-pci: Convert PCIBIOS_* return codes to errnos
  (bsc#1218260).
- mmc: sdhci: Do not invert write-protect twice (bsc#1218260).
- mmc: sdhci: Do not lock spinlock around mmc_gpio_get_ro()
  (bsc#1218260).
- iio: xilinx-ams: Don't include ams_ctrl_channels in scan_mask
  (bsc#1218260).
- counter: ti-eqep: enable clock at probe (bsc#1218260).
- kbuild: doc: Update default INSTALL_MOD_DIR from extra to
  updates (bsc#1218260).
- kbuild: Fix build target deb-pkg: ln: failed to create hard link
  (bsc#1218260).
- i2c: testunit: don't erase registers after STOP (bsc#1218260).
- i2c: testunit: discard write requests while old command is
  running (bsc#1218260).
- ata: libata-core: Fix null pointer dereference on error
  (bsc#1218260).
- ata,scsi: libata-core: Do not leak memory for ata_port struct
  members (bsc#1218260).
- iio: adc: ad7266: Fix variable checking bug (bsc#1218260).
- iio: accel: fxls8962af: select IIO_BUFFER & IIO_KFIFO_BUF
  (bsc#1218260).
- iio: chemical: bme680: Fix pressure value output (bsc#1218260).
- iio: chemical: bme680: Fix calibration data variable
  (bsc#1218260).
- iio: chemical: bme680: Fix overflows in compensate() functions
  (bsc#1218260).
- iio: chemical: bme680: Fix sensor data read operation
  (bsc#1218260).
- net: usb: ax88179_178a: improve link status logs (bsc#1218260).
- usb: gadget: printer: SS+ support (bsc#1218260).
- usb: gadget: printer: fix races against disable (bsc#1218260).
- usb: musb: da8xx: fix a resource leak in probe() (bsc#1218260).
- usb: atm: cxacru: fix endpoint checking in cxacru_bind()
  (bsc#1218260).
- usb: dwc3: core: remove lock of otg mode during gadget
  suspend/resume to avoid deadlock (bsc#1218260).
- usb: gadget: aspeed_udc: fix device address configuration
  (bsc#1218260).
- usb: typec: ucsi: glink: fix child node release in probe
  function (bsc#1218260).
- usb: ucsi: stm32: fix command completion handling (bsc#1218260).
- usb: dwc3: core: Add DWC31 version 2.00a controller
  (bsc#1218260).
- usb: dwc3: core: Workaround for CSR read timeout (bsc#1218260).
- Revert "serial: core: only stop transmit when HW fifo is empty"
  (bsc#1218260).
- serial: 8250_omap: Implementation of Errata i2310 (bsc#1218260).
- serial: imx: set receiver level before starting uart
  (bsc#1218260).
- serial: core: introduce uart_port_tx_limited_flags()
  (bsc#1218260).
- serial: bcm63xx-uart: fix tx after conversion to
  uart_port_tx_limited() (bsc#1218260).
- ALSA: hda/realtek: fix mute/micmute LEDs don't work for
  EliteBook 645/665 G11 (bsc#1218260).
- tty: mcf: MCF54418 has 10 UARTS (bsc#1218260).
- net: can: j1939: Initialize unused data in j1939_send_one()
  (bsc#1218260).
- net: can: j1939: recover socket queue on CAN bus error during
  BAM transmission (bsc#1218260).
- net: can: j1939: enhanced error handling for tightly received
  RTS messages in xtp_rx_rts_session_new (bsc#1218260).
- PCI/MSI: Fix UAF in msi_capability_init (bsc#1218260).
- cpufreq: intel_pstate: Use HWP to initialize ITMT if CPPC is
  missing (bsc#1218260).
- irqchip/loongson-eiointc: Use early_cpu_to_node() instead of
  cpu_to_node() (bsc#1218260).
- cpu/hotplug: Fix dynstate assignment in
  __cpuhp_setup_state_cpuslocked() (bsc#1218260).
- irqchip/loongson-liointc: Set different ISRs for different cores
  (bsc#1218260).
- kbuild: Install dtb files as 0644 in Makefile.dtbinst
  (bsc#1218260).
- sh: rework sync_file_range ABI (bsc#1218260).
- btrfs: zoned: fix initial free space detection (bsc#1218260).
- csky, hexagon: fix broken sys_sync_file_range (bsc#1218260).
- hexagon: fix fadvise64_64 calling conventions (bsc#1218260).
- drm/drm_file: Fix pid refcounting race (bsc#1218260).
- drm/nouveau/dispnv04: fix null pointer dereference in
  nv17_tv_get_ld_modes (bsc#1218260).
- drm/fbdev-dma: Only set smem_start is enable per module option
  (bsc#1218260).
- drm/amdgpu: avoid using null object of framebuffer
  (bsc#1218260).
- drm/i915/gt: Fix potential UAF by revoke of fence registers
  (bsc#1218260).
- drm/nouveau/dispnv04: fix null pointer dereference in
  nv17_tv_get_hd_modes (bsc#1218260).
- drm/amd/display: Send DP_TOTAL_LTTPR_CNT during detection if
  LTTPR is present (bsc#1218260).
- drm/amdgpu/atomfirmware: fix parsing of vram_info (bsc#1218260).
- batman-adv: Don't accept TT entries for out-of-spec VIDs
  (bsc#1218260).
- can: mcp251xfd: fix infinite loop when xmit fails (bsc#1218260).
- ata: ahci: Clean up sysfs file on error (bsc#1218260).
- ata: libata-core: Fix double free on error (bsc#1218260).
- ftruncate: pass a signed offset (bsc#1218260).
- syscalls: fix compat_sys_io_pgetevents_time64 usage
  (bsc#1218260).
- syscalls: fix sys_fanotify_mark prototype (bsc#1218260).
- pwm: stm32: Refuse too small period requests (bsc#1218260).
- Revert "cpufreq: amd-pstate: Fix the inconsistency in max
  frequency units" (bsc#1218260).
- mm/page_alloc: Separate THP PCP into movable and non-movable
  categories (bsc#1218260).
- arm64: dts: rockchip: Fix SD NAND and eMMC init on
  rk3308-rock-pi-s (bsc#1218260).
- arm64: dts: rockchip: Rename LED related pinctrl nodes on
  rk3308-rock-pi-s (bsc#1218260).
- arm64: dts: rockchip: Fix the value of `dlg,jack-det-rate`
  mismatch on rk3399-gru (bsc#1218260).
- ARM: dts: rockchip: rk3066a: add #sound-dai-cells to hdmi node
  (bsc#1218260).
- arm64: dts: rockchip: make poweroff(8) work on Radxa ROCK 5A
  (bsc#1218260).
- arm64: dts: rockchip: fix PMIC interrupt pin on ROCK Pi E
  (bsc#1218260).
- arm64: dts: rockchip: Add sound-dai-cells for RK3368
  (bsc#1218260).
- cxl/region: Move cxl_dpa_to_region() work to the region driver
  (bsc#1218260).
- cxl/region: Avoid null pointer dereference in region lookup
  (bsc#1218260).
- cxl/region: check interleave capability (bsc#1218260).
- serial: imx: only set receiver level if it is zero
  (bsc#1218260).
- serial: 8250_omap: Fix Errata i2310 with RX FIFO level check
  (bsc#1218260).
- tracing/net_sched: NULL pointer dereference in
  perf_trace_qdisc_reset() (bsc#1218260).
- Rename to
  patches.kernel.org/6.6.37-150-erofs-fix-NULL-dereference-of-dif-bdev_handle-.patch.