Update config files.
Disable WERROR as it breaks build. For example:
fs/qnx4/dir.c: In function 'qnx4_readdir':
fs/qnx4/dir.c:51:32: error: 'strnlen' specified bound 48 exceeds source size 16 [-Werror=stringop-overread]