Refresh patches.suse/lockdown-fix-kernel-lockdown-enforcement-issue-when-secure.patch.
Fix build failure due to undefined reference to
'lockdown_hooks_secure_boot'. This only happens when
CONFIG_SECURITY_LOCKDOWN_LSM is disabled, which is never the case for a
SUSE-supported SL-16.0 kernel, and only needed for custom bare-minimal
kernel used to run BPF selftests.