scripts/log2: Fix argument passing to splice_series
Multiple users reported seeing the following error
	Error: new series does not contain all lines from old series.
after commit 4a3b64a07ab6 ("scripts/log2: Improve automatic series.conf
modifications").

Reproduction seems to depend on the bash version; it occurs on SLE12-SP3
with 4.3.42 but not on tumbleweed with 4.4.19. The problem is caused by the
fact that `read -r -u 4 new` in splice_series reads the entire content of
$new_series as one line. $new_series is passed as a here string on file
descriptor 4, `4<<<$new_series`.

According to bash(1) for version 4.3.42, "Pathname expansion and word
splitting are not performed." for here strings. However, it appears like
word splitting might be for certain invocations (not all, for reasons I
don't understand). Work around the problem by replacing the here string
with a simpler construct.

Referenches: bsc#1094120