- Linux 6.14.6 (bsc#1012628).
- Revert "rndis_host: Flag RNDIS modems as WWAN devices"
  (bsc#1012628).
- ALSA: hda/realtek - Add more HP laptops which need mute led
  fixup (bsc#1012628).
- ALSA: usb-audio: Add retry on -EPROTO from usb_set_interface()
  (bsc#1012628).
- ALSA: usb-audio: Add second USB ID for Jabra Evolve 65 headset
  (bsc#1012628).
- ASoC: renesas: rz-ssi: Use NOIRQ_SYSTEM_SLEEP_PM_OPS()
  (bsc#1012628).
- btrfs: adjust subpage bit start based on sectorsize
  (bsc#1012628).
- btrfs: fix COW handling in run_delalloc_nocow() (bsc#1012628).
- cpufreq: intel_pstate: Unchecked MSR aceess in legacy mode
  (bsc#1012628).
- drm/fdinfo: Protect against driver unbind (bsc#1012628).
- drm/nouveau: Fix WARN_ON in nouveau_fence_context_kill()
  (bsc#1012628).
- EDAC/altera: Test the correct error reg offset (bsc#1012628).
- EDAC/altera: Set DDR and SDMMC interrupt mask before
  registration (bsc#1012628).
- i2c: imx-lpi2c: Fix clock count when probe defers (bsc#1012628).
- arm64: errata: Add missing sentinels to Spectre-BHB MIDR arrays
  (bsc#1012628).
- parisc: Fix double SIGFPE crash (bsc#1012628).
- pinctrl: airoha: fix wrong PHY LED mapping and PHY2 LED defines
  (bsc#1012628).
- perf/x86/intel: Only check the group flag for X86 leader
  (bsc#1012628).
- perf/x86/intel: KVM: Mask PEBS_ENABLE loaded for guest with
  vCPU's value (bsc#1012628).
- amd-xgbe: Fix to ensure dependent features are toggled with
  RX checksum offload (bsc#1012628).
- irqchip/qcom-mpm: Prevent crash when trying to handle non-wake
  GPIOs (bsc#1012628).
- mm/memblock: pass size instead of end to memblock_set_node()
  (bsc#1012628).
- mm/memblock: repeat setting reserved region nid if array is
  doubled (bsc#1012628).
- mmc: renesas_sdhi: Fix error handling in renesas_sdhi_probe
  (bsc#1012628).
- spi: tegra114: Don't fail set_cs_timing when delays are zero
  (bsc#1012628).
- tracing: Do not take trace_event_sem in print_event_fields()
  (bsc#1012628).
- wifi: brcm80211: fmac: Add error handling for
  brcmf_usb_dl_writeimage() (bsc#1012628).
- x86/boot/sev: Support memory acceptance in the EFI stub under
  SVSM (bsc#1012628).
- dm-bufio: don't schedule in atomic context (bsc#1012628).
- dm-integrity: fix a warning on invalid table line (bsc#1012628).
- dm: always update the array size in realloc_argv on success
  (bsc#1012628).
- drm/amdgpu: Fix offset for HDP remap in nbio v7.11
  (bsc#1012628).
- drm: Select DRM_KMS_HELPER from DRM_DEBUG_DP_MST_TOPOLOGY_REFS
  (bsc#1012628).
- iommu/amd: Fix potential buffer overflow in parse_ivrs_acpihid
  (bsc#1012628).
- iommu/arm-smmu-v3: Fix iommu_device_probe bug due to duplicated
  stream ids (bsc#1012628).
- iommu/arm-smmu-v3: Fix pgsize_bit for sva domains (bsc#1012628).
- iommu/vt-d: Apply quirk_iommu_igfx for 8086:0044 (QM57/QS57)
  (bsc#1012628).
- iommu: Fix two issues in iommu_copy_struct_from_user()
  (bsc#1012628).
- platform/x86/amd: pmc: Require at least 2.5 seconds between
  HW sleep cycles (bsc#1012628).
- platform/x86/intel-uncore-freq: Fix missing uncore sysfs during
  CPU hotplug (bsc#1012628).
- ksmbd: fix use-after-free in ksmbd_session_rpc_open
  (bsc#1012628).
- ksmbd: fix use-after-free in kerberos authentication
  (bsc#1012628).
- ksmbd: fix use-after-free in session logoff (bsc#1012628).
- smb: client: fix zero length for mkdir POSIX create context
  (bsc#1012628).
- cpufreq: Avoid using inconsistent policy->min and policy->max
  (bsc#1012628).
- cpufreq: Fix setting policy limits when frequency tables are
  used (bsc#1012628).
- tracing: Fix oob write in trace_seq_to_buffer() (bsc#1012628).
- bcachefs: Remove incorrect __counted_by annotation
  (bsc#1012628).
- drm/amd/display: Default IPS to RCG_IN_ACTIVE_IPS2_IN_OFF
  (bsc#1012628).
- ASoC: soc-core: Stop using of_property_read_bool() for
  non-boolean properties (bsc#1012628).
- ASoC: cs-amp-lib-test: Don't select SND_SOC_CS_AMP_LIB
  (bsc#1012628).
- firmware: cs_dsp: tests: Depend on FW_CS_DSP rather then
  enabling it (bsc#1012628).
- ASoC: soc-pcm: Fix hw_params() and DAPM widget sequence
  (bsc#1012628).
- book3s64/radix : Align section vmemmap start address to
  PAGE_SIZE (bsc#1012628).
- powerpc64/ftrace: fix module loading without patchable function
  entries (bsc#1012628).
- pinctrl: imx: Return NULL if no group is matched and found
  (bsc#1012628).
- powerpc/boot: Check for ld-option support (bsc#1012628).
- ASoC: Intel: sof_sdw: Add NULL check in
  asoc_sdw_rt_dmic_rtd_init() (bsc#1012628).
- iommu/arm-smmu-v3: Add missing S2FWB feature detection
  (bsc#1012628).
- ALSA: hda/realtek - Enable speaker for HP platform
  (bsc#1012628).
- drm/i915/pxp: fix undefined reference to
  `intel_pxp_gsccs_is_ready_for_sessions' (bsc#1012628).
- wifi: iwlwifi: back off on continuous errors (bsc#1012628).
- wifi: iwlwifi: don't warn if the NIC is gone in resume
  (bsc#1012628).
- wifi: iwlwifi: fix the check for the SCRATCH register upon
  resume (bsc#1012628).
- wifi: plfxlc: Remove erroneous assert in plfxlc_mac_release
  (bsc#1012628).
- powerpc/boot: Fix dash warning (bsc#1012628).
- vxlan: vnifilter: Fix unlocked deletion of default FDB entry
  (bsc#1012628).
- xsk: Fix race condition in AF_XDP generic RX path (bsc#1012628).
- xsk: Fix offset calculation in unaligned mode (bsc#1012628).
- net/mlx5e: Use custom tunnel header for vxlan gbp (bsc#1012628).
- net/mlx5: E-Switch, Initialize MAC Address for Default GID
  (bsc#1012628).
- net/mlx5e: TC, Continue the attr process even if encap entry
  is invalid (bsc#1012628).
- net/mlx5e: Fix lock order in
  mlx5e_tx_reporter_ptpsq_unhealthy_recover (bsc#1012628).
- net/mlx5: E-switch, Fix error handling for enabling roce
  (bsc#1012628).
- accel/ivpu: Correct DCT interrupt handling (bsc#1012628).
- spi: spi-mem: Add fix to avoid divide error (bsc#1012628).
- ASoC: amd: acp: Fix NULL pointer deref in acp_i2s_set_tdm_slot
  (bsc#1012628).
- cpufreq: Introduce policy->boost_supported flag (bsc#1012628).
- cpufreq: acpi: Set policy->boost_supported (bsc#1012628).
- cpufreq: ACPI: Re-sync CPU boost state on system resume
  (bsc#1012628).
- Bluetooth: hci_conn: Fix not setting conn_timeout for Broadcast
  Receiver (bsc#1012628).
- Bluetooth: hci_conn: Fix not setting timeout for BIG Create Sync
  (bsc#1012628).
- Bluetooth: btintel_pcie: Avoid redundant buffer allocation
  (bsc#1012628).
- Bluetooth: btusb: avoid NULL pointer dereference in
  skb_dequeue() (bsc#1012628).
- Bluetooth: btintel_pcie: Add additional to checks to clear
  TX/RX paths (bsc#1012628).
- Bluetooth: L2CAP: copy RX timestamp to new fragments
  (bsc#1012628).
- net: mscc: ocelot: delete PVID VLAN when readding it as non-PVID
  (bsc#1012628).
- octeon_ep_vf: Resolve netdevice usage count issue (bsc#1012628).
- bnxt_en: improve TX timestamping FIFO configuration
  (bsc#1012628).
- rtase: Modify the condition used to detect overflow in
  rtase_calc_time_mitigation (bsc#1012628).
- net: ethernet: mtk-star-emac: fix spinlock recursion issues
  on rx/tx poll (bsc#1012628).
- net: ethernet: mtk-star-emac: rearm interrupts in rx_poll only
  when advised (bsc#1012628).
- net: ethernet: mtk_eth_soc: sync mtk_clks_source_name array
  (bsc#1012628).
- pds_core: make pdsc_auxbus_dev_del() void (bsc#1012628).
- pds_core: specify auxiliary_device to be created (bsc#1012628).
- pds_core: remove write-after-free of client_id (bsc#1012628).
- net_sched: drr: Fix double list add in class with netem as
  child qdisc (bsc#1012628).
- net_sched: hfsc: Fix a UAF vulnerability in class with netem
  as child qdisc (bsc#1012628).
- net_sched: ets: Fix double list add in class with netem as
  child qdisc (bsc#1012628).
- net_sched: qfq: Fix double list add in class with netem as
  child qdisc (bsc#1012628).
- ice: Don't check device type when checking GNSS presence
  (bsc#1012628).
- ice: Remove unnecessary ice_is_e8xx() functions (bsc#1012628).
- ice: fix Get Tx Topology AQ command error on E830 (bsc#1012628).
- ice: Check VF VSI Pointer Value in ice_vc_add_fdir_fltr()
  (bsc#1012628).
- idpf: fix offloads support for encapsulated packets
  (bsc#1012628).
- scsi: ufs: core: Remove redundant query_complete trace
  (bsc#1012628).
- drm/xe/guc: Fix capture of steering registers (bsc#1012628).
- pinctrl: qcom: Fix PINGROUP definition for sm8750 (bsc#1012628).
- nvme-pci: fix queue unquiesce check on slot_reset (bsc#1012628).
- drm/tests: shmem: Fix memleak (bsc#1012628).
- drm/mipi-dbi: Fix blanking for non-16 bit formats (bsc#1012628).
- net: dlink: Correct endianness handling of led_mode
  (bsc#1012628).
- net: mdio: mux-meson-gxl: set reversed bit when using internal
  phy (bsc#1012628).
- idpf: fix potential memory leak on kcalloc() failure
  (bsc#1012628).
- idpf: protect shutdown from reset (bsc#1012628).
- igc: fix lock order in igc_ptp_reset (bsc#1012628).
- net: ethernet: mtk_eth_soc: fix SER panic with 4GB+ RAM
  (bsc#1012628).
- net: dsa: felix: fix broken taprio gate states after clock jump
  (bsc#1012628).
- net: ipv6: fix UDPv6 GSO segmentation with NAT (bsc#1012628).
- ALSA: hda/realtek: Fix built-mic regression on other ASUS models
  (bsc#1012628).
- bnxt_en: Fix error handling path in bnxt_init_chip()
  (bsc#1012628).
- bnxt_en: Fix ethtool selftest output in one of the failure cases
  (bsc#1012628).
- bnxt_en: Add missing skb_mark_for_recycle() in bnxt_rx_vlan()
  (bsc#1012628).
- bnxt_en: call pci_alloc_irq_vectors() after bnxt_reserve_rings()
  (bsc#1012628).
- bnxt_en: Fix coredump logic to free allocated buffer
  (bsc#1012628).
- bnxt_en: Fix out-of-bound memcpy() during ethtool -w
  (bsc#1012628).
- bnxt_en: Fix ethtool -d byte order for 32-bit values
  (bsc#1012628).
- nvme-tcp: fix premature queue removal and I/O failover
  (bsc#1012628).
- nvme-tcp: select CONFIG_TLS from CONFIG_NVME_TCP_TLS
  (bsc#1012628).
- nvmet-tcp: select CONFIG_TLS from CONFIG_NVME_TARGET_TCP_TLS
  (bsc#1012628).
- ASoC: stm32: sai: skip useless iterations on kernel rate loop
  (bsc#1012628).
- ASoC: stm32: sai: add a check on minimal kernel frequency
  (bsc#1012628).
- ASoC: simple-card-utils: Fix pointer check in
  graph_util_parse_link_direction (bsc#1012628).
- bnxt_en: fix module unload sequence (bsc#1012628).
- net: use sock_gen_put() when sk_state is TCP_TIME_WAIT
  (bsc#1012628).
- ptp: ocp: Fix NULL dereference in Adva board SMA sysfs
  operations (bsc#1012628).
- net: lan743x: Fix memleak issue when GSO enabled (bsc#1012628).
- net: fec: ERR007885 Workaround for conventional TX
  (bsc#1012628).
- octeon_ep: Fix host hang issue during device reboot
  (bsc#1012628).
- net: hns3: store rx VLAN tag offload state for VF (bsc#1012628).
- net: hns3: fix an interrupt residual problem (bsc#1012628).
- net: hns3: fixed debugfs tm_qset size (bsc#1012628).
- net: hns3: defer calling ptp_clock_register() (bsc#1012628).
- net: vertexcom: mse102x: Fix possible stuck of SPI interrupt
  (bsc#1012628).
- net: vertexcom: mse102x: Fix LEN_MASK (bsc#1012628).
- net: vertexcom: mse102x: Add range check for CMD_RTS
  (bsc#1012628).
- net: vertexcom: mse102x: Fix RX error handling (bsc#1012628).
- mm, slab: clean up slab->obj_exts always (bsc#1012628).
- accel/ivpu: Abort all jobs after command queue unregister
  (bsc#1012628).
- accel/ivpu: Fix locking order in ivpu_job_submit (bsc#1012628).
- accel/ivpu: Add handling of
  VPU_JSM_STATUS_MVNCI_CONTEXT_VIOLATION_HW (bsc#1012628).
- drm/xe: Invalidate L3 read-only cachelines for geometry streams
  too (bsc#1012628).
- platform/x86: alienware-wmi-wmax: Add support for Alienware
  m15 R7 (bsc#1012628).
- ublk: add helper of ublk_need_map_io() (bsc#1012628).
- ublk: properly serialize all FETCH_REQs (bsc#1012628).
- ublk: move device reset into ublk_ch_release() (bsc#1012628).
- ublk: improve detection and handling of ublk server exit
  (bsc#1012628).
- ublk: remove __ublk_quiesce_dev() (bsc#1012628).
- ublk: simplify aborting ublk request (bsc#1012628).
- ublk: fix race between io_uring_cmd_complete_in_task and
  ublk_cancel_cmd (bsc#1012628).
- sch_htb: make htb_qlen_notify() idempotent (bsc#1012628).
- sch_drr: make drr_qlen_notify() idempotent (bsc#1012628).
- sch_hfsc: make hfsc_qlen_notify() idempotent (bsc#1012628).
- sch_qfq: make qfq_qlen_notify() idempotent (bsc#1012628).
- sch_ets: make est_qlen_notify() idempotent (bsc#1012628).
- firmware: arm_scmi: Balance device refcount when destroying
  devices (bsc#1012628).
- firmware: arm_ffa: Skip Rx buffer ownership release if not
  acquired (bsc#1012628).
- arm64: dts: imx95: Correct the range of PCIe app-reg region
  (bsc#1012628).
- ARM: dts: opos6ul: add ksz8081 phy properties (bsc#1012628).
- arm64: dts: st: Adjust interrupt-controller for stm32mp25 SoCs
  (bsc#1012628).
- arm64: dts: st: Use 128kB size for aliased GIC400 register
  access on stm32mp25 SoCs (bsc#1012628).
- block: introduce zone capacity helper (bsc#1012628).
- btrfs: zoned: skip reporting zone for new block group
  (bsc#1012628).
- kernel: param: rename locate_module_kobject (bsc#1012628).
- kernel: globalize lookup_or_create_module_kobject()
  (bsc#1012628).
- drivers: base: handle module_kobject creation (bsc#1012628).
- btrfs: expose per-inode stable writes flag (bsc#1012628).
- btrfs: pass struct btrfs_inode to btrfs_read_locked_inode()
  (bsc#1012628).
- btrfs: pass struct btrfs_inode to btrfs_iget_locked()
  (bsc#1012628).
- btrfs: fix the inode leak in btrfs_iget() (bsc#1012628).
- drm/amd/display: Add scoped mutexes for amdgpu_dm_dhcp
  (bsc#1012628).
- drm/amd/display: Fix slab-use-after-free in hdcp (bsc#1012628).
- bcachefs: Change btree_insert_node() assertion to error
  (bsc#1012628).
- dm: fix copying after src array boundaries (bsc#1012628).
- Rename to
  patches.kernel.org/6.14.6-108-ALSA-ump-Fix-buffer-overflow-at-UMP-SysEx-mess.patch.