scripts/python/series_merge_tool: fix for labels == None
I see:
$ git mergetool
Merging:
series.conf

Normal merge conflict for 'series.conf':
  {local}: modified file
  {remote}: modified file
Traceback (most recent call last):
  File "scripts/git_sort/merge_tool", line 94, in <module>
    if merge(tmp_local.name, args.base, args.remote, args.labels):
  File "scripts/git_sort/merge_tool", line 55, in merge
    return subprocess.call(cmd + labels + [local, base, remote]) == 0
TypeError: can only concatenate list (not "NoneType") to list
merge of series.conf failed

Append labels to cmd directly to avoid this. (And simplify the
appending.)

Fixes: 27e7b0106c7c ("scripts/python/series_merge_tool: Optimize fast path cases")