- Linux 4.19.3 (bnc#1012628).
- powerpc/traps: restore recoverability of machine_check
  interrupts (bnc#1012628).
- powerpc/64/module: REL32 relocation range check (bnc#1012628).
- powerpc/mm: Fix page table dump to work on Radix (bnc#1012628).
- powerpc/mm: fix always true/false warning in slice.c
  (bnc#1012628).
- drm/amd/display: fix bug of accessing invalid memory
  (bnc#1012628).
- Input: wm97xx-ts - fix exit path (bnc#1012628).
- powerpc/Makefile: Fix PPC_BOOK3S_64 ASFLAGS (bnc#1012628).
- powerpc/eeh: Fix possible null deref in eeh_dump_dev_log()
  (bnc#1012628).
- tty: check name length in tty_find_polling_driver()
  (bnc#1012628).
- tracing/kprobes: Check the probe on unloaded module correctly
  (bnc#1012628).
- drm/nouveau/secboot/acr: fix memory leak (bnc#1012628).
- drm/amdgpu/powerplay: fix missing break in switch statements
  (bnc#1012628).
- ARM: imx_v6_v7_defconfig: Select CONFIG_TMPFS_POSIX_ACL
  (bnc#1012628).
- powerpc/nohash: fix undefined behaviour when testing page size
  support (bnc#1012628).
- drm/msm/gpu: fix parameters in function
  msm_gpu_crashstate_capture (bnc#1012628).
- drm/msm/disp/dpu: Use proper define for drm_encoder_init()
  'encoder_type' (bnc#1012628).
- drm/msm: dpu: Allow planes to extend past active display
  (bnc#1012628).
- powerpc/mm: Don't report hugepage tables as memory leaks when
  using kmemleak (bnc#1012628).
- drm/omap: fix memory barrier bug in DMM driver (bnc#1012628).
- drm/amd/display: Raise dispclk value for dce120 by 15%
  (bnc#1012628).
- drm/amd/display: fix gamma not being applied (bnc#1012628).
- drm/hisilicon: hibmc: Do not carry error code in HiBMC
  framebuffer pointer (bnc#1012628).
- media: pci: cx23885: handle adding to list failure
  (bnc#1012628).
- media: coda: don't overwrite h.264 profile_idc on decoder
  instance (bnc#1012628).
- MIPS: kexec: Mark CPU offline before disabling local IRQ
  (bnc#1012628).
- powerpc/boot: Ensure _zimage_start is a weak symbol
  (bnc#1012628).
- powerpc/memtrace: Remove memory in chunks (bnc#1012628).
- MIPS/PCI: Call pcie_bus_configure_settings() to set MPS/MRRS
  (bnc#1012628).
- staging: erofs: fix a missing endian conversion (bnc#1012628).
- serial: 8250_of: Fix for lack of interrupt support
  (bnc#1012628).
- sc16is7xx: Fix for multi-channel stall (bnc#1012628).
- media: tvp5150: fix width alignment during set_selection()
  (bnc#1012628).
- powerpc/selftests: Wait all threads to join (bnc#1012628).
- staging:iio:ad7606: fix voltage scales (bnc#1012628).
- drm: rcar-du: Update Gen3 output limitations (bnc#1012628).
- drm/amdgpu: Fix SDMA TO after GPU reset v3 (bnc#1012628).
- staging: most: video: fix registration of an empty comp
  core_component (bnc#1012628).
- 9p locks: fix glock.client_id leak in do_lock (bnc#1012628).
- udf: Prevent write-unsupported filesystem to be remounted
  read-write (bnc#1012628).
- ARM: dts: imx6ull: keep IMX6UL_ prefix for signals on both
  i.MX6UL and i.MX6ULL (bnc#1012628).
- media: ov5640: fix mode change regression (bnc#1012628).
- 9p: clear dangling pointers in p9stat_free (bnc#1012628).
- drm/amdgpu: fix integer overflow test in amdgpu_bo_list_create()
  (bnc#1012628).
- media: ov5640: fix restore of last mode set (bnc#1012628).
- ovl: fix error handling in ovl_verify_set_fh() (bnc#1012628).
- ovl: fix recursive oi->lock in ovl_link() (bnc#1012628).
- ovl: check whiteout in ovl_create_over_whiteout() (bnc#1012628).
- ovl: automatically enable redirect_dir on metacopy=on
  (bnc#1012628).
- serial: sh-sci: Fix could not remove dev_attr_rx_fifo_timeout
  (bnc#1012628).
- scsi: qla2xxx: Fix incorrect port speed being set for FC
  adapters (bnc#1012628).
- scsi: qla2xxx: Fix process response queue for ISP26XX and above
  (bnc#1012628).
- scsi: qla2xxx: Remove stale debug trace message from tcm_qla2xxx
  (bnc#1012628).
- scsi: qla2xxx: Fix early srb free on abort (bnc#1012628).
- scsi: qla2xxx: shutdown chip if reset fail (bnc#1012628).
- scsi: qla2xxx: Reject bsg request if chip is down (bnc#1012628).
- scsi: qla2xxx: Fix re-using LoopID when handle is in use
  (bnc#1012628).
- scsi: qla2xxx: Fix for double free of SRB structure
  (bnc#1012628).
- scsi: qla2xxx: Fix NVMe session hang on unload (bnc#1012628).
- scsi: qla2xxx: Fix NVMe Target discovery (bnc#1012628).
- scsi: qla2xxx: Fix duplicate switch database entries
  (bnc#1012628).
- scsi: qla2xxx: Fix driver hang when FC-NVMe LUNs are configured
  (bnc#1012628).
- vfs: fix FIGETBSZ ioctl on an overlayfs file (bnc#1012628).
- fuse: Fix use-after-free in fuse_dev_do_read() (bnc#1012628).
- fuse: Fix use-after-free in fuse_dev_do_write() (bnc#1012628).
- fuse: fix blocked_waitq wakeup (bnc#1012628).
- fuse: set FR_SENT while locked (bnc#1012628).
- drm/msm: fix OF child-node lookup (bnc#1012628).
- arm64: dts: stratix10: Support Ethernet Jumbo frame
  (bnc#1012628).
- arm64: dts: stratix10: fix multicast filtering (bnc#1012628).
- clk: meson-gxbb: set fclk_div3 as CLK_IS_CRITICAL (bnc#1012628).
- clk: meson: axg: mark fdiv2 and fdiv3 as critical (bnc#1012628).
- zram: close udev startup race condition as default groups
  (bnc#1012628).
- MIPS: Loongson-3: Fix CPU UART irq delivery problem
  (bnc#1012628).
- MIPS: Loongson-3: Fix BRIDGE irq delivery problem (bnc#1012628).
- xtensa: add NOTES section to the linker script (bnc#1012628).
- xtensa: make sure bFLT stack is 16 byte aligned (bnc#1012628).
- xtensa: fix boot parameters address translation (bnc#1012628).
- um: Drop own definition of PTRACE_SYSEMU/_SINGLESTEP
  (bnc#1012628).
- clk: s2mps11: Fix matching when built as module and DT node
  contains compatible (bnc#1012628).
- clk: at91: Fix division by zero in PLL recalc_rate()
  (bnc#1012628).
- clk: sunxi-ng: h6: fix bus clocks' divider position
  (bnc#1012628).
- clk: rockchip: fix wrong mmc sample phase shift for rk3328
  (bnc#1012628).
- clk: rockchip: Fix static checker warning in
  rockchip_ddrclk_get_parent call (bnc#1012628).
- libceph: bump CEPH_MSG_MAX_DATA_LEN (bnc#1012628).
- Revert "ceph: fix dentry leak in splice_dentry()" (bnc#1012628).
- thermal: core: Fix use-after-free in
  thermal_cooling_device_destroy_sysfs (bnc#1012628).
- mach64: fix display corruption on big endian machines
  (bnc#1012628).
- mach64: fix image corruption due to reading accelerator
  registers (bnc#1012628).
- acpi/nfit, x86/mce: Handle only uncorrectable machine checks
  (bnc#1012628).
- acpi/nfit, x86/mce: Validate a MCE's address before using it
  (bnc#1012628).
- acpi, nfit: Fix ARS overflow continuation (bnc#1012628).
- reset: hisilicon: fix potential NULL pointer dereference
  (bnc#1012628).
- crypto: hisilicon - Fix NULL dereference for same dst and src
  (bnc#1012628).
- crypto: hisilicon - Fix reference after free of memories on
  error path (bnc#1012628).
- vhost/scsi: truncate T10 PI iov_iter to prot_bytes
  (bnc#1012628).
- scsi: qla2xxx: Initialize port speed to avoid setting lower
  speed (bnc#1012628).
- SCSI: fix queue cleanup race before queue initialization is done
  (bnc#1012628).
- Revert "powerpc/8xx: Use L1 entry APG to handle _PAGE_ACCESSED
  for CONFIG_SWAP" (bnc#1012628).
- soc: ti: QMSS: Fix usage of irq_set_affinity_hint (bnc#1012628).
- ocfs2: fix a misuse a of brelse after failing
  ocfs2_check_dir_entry (bnc#1012628).
- ocfs2: free up write context when direct IO failed
  (bnc#1012628).
- mm: thp: relax __GFP_THISNODE for MADV_HUGEPAGE mappings
  (bnc#1012628).
- memory_hotplug: cond_resched in __remove_pages (bnc#1012628).
- netfilter: conntrack: fix calculation of next bucket number
  in early_drop (bnc#1012628).
- ARM: 8809/1: proc-v7: fix Thumb annotation of
  cpu_v7_hvc_switch_mm (bnc#1012628).
- bonding/802.3ad: fix link_failure_count tracking (bnc#1012628).
- mtd: spi-nor: cadence-quadspi: Return error code in
  cqspi_direct_read_execute() (bnc#1012628).
- mtd: nand: Fix nanddev_neraseblocks() (bnc#1012628).
- mtd: docg3: don't set conflicting BCH_CONST_PARAMS option
  (bnc#1012628).
- hwmon: (core) Fix double-free in __hwmon_device_register()
  (bnc#1012628).
- perf cs-etm: Correct CPU mode for samples (bnc#1012628).
- perf stat: Handle different PMU names with common prefix
  (bnc#1012628).
- perf callchain: Honour the ordering of
  PERF_CONTEXT_{USER,KERNEL,etc} (bnc#1012628).
- perf intel-pt/bts: Calculate cpumode for synthesized samples
  (bnc#1012628).
- perf intel-pt: Insert callchain context into synthesized
  callchains (bnc#1012628).
- of, numa: Validate some distance map rules (bnc#1012628).
- x86/cpu/vmware: Do not trace vmware_sched_clock() (bnc#1012628).
- x86/hyper-v: Enable PIT shutdown quirk (bnc#1012628).
- termios, tty/tty_baudrate.c: fix buffer overrun (bnc#1012628).
- arch/alpha, termios: implement BOTHER, IBSHIFT and termios2
  (bnc#1012628).
- watchdog/core: Add missing prototypes for weak functions
  (bnc#1012628).
- btrfs: fix pinned underflow after transaction aborted
  (bnc#1012628).
- Btrfs: fix missing data checksums after a ranged fsync (msync)
  (bnc#1012628).
- Btrfs: fix cur_offset in the error case for nocow (bnc#1012628).
- Btrfs: fix infinite loop on inode eviction after deduplication
  of eof block (bnc#1012628).
- Btrfs: fix data corruption due to cloning of eof block
  (bnc#1012628).
- btrfs: tree-checker: Fix misleading group system information
  (bnc#1012628).
- clockevents/drivers/i8253: Add support for PIT shutdown quirk
  (bnc#1012628).
- ext4: add missing brelse() update_backups()'s error path
  (bnc#1012628).
- ext4: add missing brelse() in set_flexbg_block_bitmap()'s
  error path (bnc#1012628).
- ext4: add missing brelse() add_new_gdb_meta_bg()'s error path
  (bnc#1012628).
- ext4: avoid potential extra brelse in
  setup_new_flex_group_blocks() (bnc#1012628).
- ext4: missing !bh check in ext4_xattr_inode_write()
  (bnc#1012628).
- ext4: fix possible inode leak in the retry loop of
  ext4_resize_fs() (bnc#1012628).
- ext4: avoid buffer leak on shutdown in ext4_mark_iloc_dirty()
  (bnc#1012628).
- ext4: avoid buffer leak in ext4_orphan_add() after prior errors
  (bnc#1012628).
- ext4: fix missing cleanup if ext4_alloc_flex_bg_array() fails
  while resizing (bnc#1012628).
- ext4: avoid possible double brelse() in add_new_gdb() on error
  path (bnc#1012628).
- ext4: fix possible leak of sbi->s_group_desc_leak in error path
  (bnc#1012628).
- ext4: fix possible leak of s_journal_flag_rwsem in error path
  (bnc#1012628).
- ext4: fix buffer leak in ext4_xattr_get_block() on error path
  (bnc#1012628).
- ext4: release bs.bh before re-using in ext4_xattr_block_find()
  (bnc#1012628).
- ext4: fix buffer leak in ext4_xattr_move_to_block() on error
  path (bnc#1012628).
- ext4: fix buffer leak in ext4_expand_extra_isize_ea() on error
  path (bnc#1012628).
- ext4: fix buffer leak in __ext4_read_dirblock() on error path
  (bnc#1012628).
- mount: Retest MNT_LOCKED in do_umount (bnc#1012628).
- mount: Don't allow copying MNT_UNBINDABLE|MNT_LOCKED mounts
  (bnc#1012628).
- mount: Prevent MNT_DETACH from disconnecting locked mounts
  (bnc#1012628).
- mnt: fix __detach_mounts infinite loop (bnc#1012628).
- uapi: fix linux/kfd_ioctl.h userspace compilation errors
  (bnc#1012628).
- ARM: cpuidle: Don't register the driver when back-end init
  returns -ENXIO (bnc#1012628).
- kdb: use correct pointer when 'btc' calls 'btt' (bnc#1012628).
- kdb: print real address of pointers instead of hashed addresses
  (bnc#1012628).
- sunrpc: correct the computation for page_ptr when truncating
  (bnc#1012628).
- NFSv4: Don't exit the state manager without clearing
  NFS4CLNT_MANAGER_RUNNING (bnc#1012628).
- nfsd: COPY and CLONE operations require the saved filehandle
  to be set (bnc#1012628).
- rtc: hctosys: Add missing range error reporting (bnc#1012628).
- fuse: fix use-after-free in fuse_direct_IO() (bnc#1012628).
- fuse: fix leaked notify reply (bnc#1012628).
- fuse: fix possibly missed wake-up after abort (bnc#1012628).
- selinux: check length properly in SCTP bind hook (bnc#1012628).
- gfs2: Put bitmap buffers in put_super (bnc#1012628).
- gfs2: Fix metadata read-ahead during truncate (2) (bnc#1012628).
- libata: blacklist SAMSUNG MZ7TD256HAFV-000L9 SSD (bnc#1012628).
- crypto: user - fix leaking uninitialized memory to userspace
  (bnc#1012628).
- lib/ubsan.c: don't mark __ubsan_handle_builtin_unreachable as
  noreturn (bnc#1012628).
- hugetlbfs: fix kernel BUG at
  fs/hugetlbfs/inode.c:444! (bnc#1012628).
- mm/swapfile.c: use kvzalloc for swap_info_struct allocation
  (bnc#1012628).
- efi/arm/libstub: Pack FDT after populating it (bnc#1012628).
- mm: don't reclaim inodes with many attached pages (bnc#1012628).
- scripts/spdxcheck.py: make python3 compliant (bnc#1012628).
- drm/rockchip: Allow driver to be shutdown on reboot/kexec
  (bnc#1012628).
- drm/amdgpu: Fix typo in amdgpu_vmid_mgr_init (bnc#1012628).
- drm/amdgpu: add missing CHIP_HAINAN in
  amdgpu_ucode_get_load_type (bnc#1012628).
- drm/amdgpu: Suppress keypresses from ACPI_VIDEO events
  (bnc#1012628).
- drm/nouveau: Check backlight IDs are >= 0, not > 0
  (bnc#1012628).
- drm/nouveau: Fix nv50_mstc->best_encoder() (bnc#1012628).
- drm/amd/powerplay: Enable/Disable NBPSTATE on On/OFF of UVD
  (bnc#1012628).
- drm/etnaviv: fix bogus fence complete check in timeout handler
  (bnc#1012628).
- drm/dp_mst: Check if primary mstb is null (bnc#1012628).
- drm: panel-orientation-quirks: Add quirk for Acer One 10 (S1003)
  (bnc#1012628).
- drm/i915/dp: Link train Fallback on eDP only if fallback link
  BW can fit panel's native mode (bnc#1012628).
- drm/i915: Use the correct crtc when sanitizing plane mapping
  (bnc#1012628).
- drm/i915: Restore vblank interrupts earlier (bnc#1012628).
- drm/i915: Don't unset intel_connector->mst_port (bnc#1012628).
- drm/i915: Skip vcpi allocation for MSTB ports that are gone
  (bnc#1012628).
- drm/i915: Large page offsets for pread/pwrite (bnc#1012628).
- drm/i915/dp: Fix link retraining comment in
  intel_dp_long_pulse() (bnc#1012628).
- drm/i915/dp: Restrict link retrain workaround to external
  monitors (bnc#1012628).
- drm/i915/icl: Fix the macros for DFLEXDPMLE register bits
  (bnc#1012628).
- drm/i915/hdmi: Add HDMI 2.0 audio clock recovery N values
  (bnc#1012628).
- drm/i915: Mark up GTT sizes as u64 (bnc#1012628).
- drm/i915: Fix error handling for the NV12 fb dimensions check
  (bnc#1012628).
- drm/i915: Fix ilk+ watermarks when disabling pipes
  (bnc#1012628).
- drm/i915: Compare user's 64b GTT offset even on 32b
  (bnc#1012628).
- drm/i915: Don't oops during modeset shutdown after lpe audio
  deinit (bnc#1012628).
- drm/i915: Mark pin flags as u64 (bnc#1012628).
- drm/i915/ringbuffer: Delay after EMIT_INVALIDATE for gen4/gen5
  (bnc#1012628).
- drm/i915/execlists: Force write serialisation into context
  image vs execution (bnc#1012628).
- drm/i915: Fix possible race in intel_dp_add_mst_connector()
  (bnc#1012628).
- drm/i915: Fix NULL deref when re-enabling HPD IRQs on systems
  with MST (bnc#1012628).
- drm/i915: Fix hpd handling for pins with two encoders
  (bnc#1012628).
- CONFIG_XEN_PV breaks xen_create_contiguous_region on ARM
  (bnc#1012628).
- Revert "ACPICA: AML interpreter: add region addresses in global
  list during initialization" (bnc#1012628).