scripts/python/git_sort/git_sort.yaml: fix driver-core tree
driver-core-next does not exist anymore [1]. Adapt to that and fix the
error:

  Error: Could not read revision
  "refs/remotes/gregkh/driver-core/driver-core-next". Perhaps you need to
  fetch from remote "gregkh/driver-core" "sorted patches" section of
  series.conf failed check. Please read "scripts/git_sort/README.md", in
  particular the section "Refreshing the order of patches in series.conf".

[1] https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core.git/