Refresh patches.suse/selftests-bpf-Clean-up-open-coded-gettid-syscall-inv.patch.
Fix following BPF selftests compilation error due to missing dependency.

  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/ns_current_pid_tgid.c: In function ‘test_current_pid_tgid’:
  /home/runner/work/libbpf/libbpf/.kernel/tools/testing/selftests/bpf/prog_tests/ns_current_pid_tgid.c:31:9: error: invalid type argument of unary ‘*’ (have ‘pid_t’ {aka ‘int’})
     31 |         *pid = sys_gettid();
        |         ^~~~