rpm/kernel-binary.spec.in: fix klp_symbols macro
The commit below removed openSUSE filter from %ifs of the klp_symbols
definition. But it removed -c of grep too and that causes:

error: syntax error in expression:  01 && (  || 1 )
error:                                        ^
error: unmatched (:  01 && (  || 1 )
error:                     ^
error: kernel-default.spec:137: bad %if condition:  01 && (  || 1 )

So reintroduce -c to the PTF's grep.

Fixes: fd0b293bebaf (kernel-binary.spec.in: Enable klp_symbols on openSUSE Tumbleweed (boo#1229042).)