scripts: Adjust for pygit2 update
pygit2 removes shortened enum names in v1.15.0~19, it breaks git_sort:

    git mergetool --tool=git-sort series.conf
    Merging:
    series.conf

    Normal merge conflict for 'series.conf':
      {local}: modified file
      {remote}: modified file
    3 commits added, 0 commits removed from base to remote.
    merge: warning: conflicts during merge
    Warning: conflicts outside of sorted section, leaving merged result in series.conf.merged1865758
    Traceback (most recent call last):
      File "/git/suse/kernel-source-5.14/scripts/git_sort/merge_tool.py", line 144, in <module>
        lib.update_tags(index, to_update)
      File "/git/suse/kernel-source-5.14/scripts/git_sort/lib.py", line 513, in update_tags
        patch.change(tag_name, index.describe(entry.dest.index))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/git/suse/kernel-source-5.14/scripts/git_sort/git_sort.py", line 647, in describe
        objects = [(obj_tag.get_object(), tag,)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/git/suse/kernel-source-5.14/scripts/git_sort/git_sort.py", line 652, in <listcomp>
        ] if obj_tag.type == pygit2.GIT_OBJ_TAG]
                             ^^^^^^^^^^^^^^^^^^
    AttributeError: module 'pygit2_wrapper' has no attribute 'GIT_OBJ_TAG'. Did you mean: 'GIT_OBJECT_TAG'?
    merge of series.conf failed

Adjust the code for the new library names but add aliases when the old
library is detected not to break legacy users.