scripts/merging/references: Fix forgotten remame
Traceback (most recent call last):
  File "src/clone_work_space/scripts/merging/references", line 51, in <module>
    p.change("References", " ".join(merged_refs), Patch.ChangeMode.ALL_WITH_ONE)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/clone_work_space/scripts/merging/../python/suse_git/patch.py", line 166, in change
    raise KeyError("Tag \"%s\" not found" % (tag,))
KeyError: 'Tag "References" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/clone_work_space/scripts/merging/references", line 54, in <module>
    if p == merged_patch:
            ^^^^^^^^^^^^
NameError: name 'merged_patch' is not defined

Fixes: 6f48718a2d3 ("scripts/merging/references: Fix driver mode results file")