- Linux 6.5.5 (bsc#1012628).
- iomap: Fix possible overflow condition in
  iomap_write_delalloc_scan (bsc#1012628).
- autofs: fix memory leak of waitqueues in autofs_catatonic_mode
  (bsc#1012628).
- btrfs: handle errors properly in update_inline_extent_backref()
  (bsc#1012628).
- btrfs: output extra debug info if we failed to find an inline
  backref (bsc#1012628).
- locks: fix KASAN: use-after-free in
  trace_event_raw_event_filelock_lock (bsc#1012628).
- ACPICA: Add AML_NO_OPERAND_RESOLVE flag to Timer (bsc#1012628).
- kernel/fork: beware of __put_task_struct() calling context
  (bsc#1012628).
- rcuscale: Move rcu_scale_writer()
  schedule_timeout_uninterruptible() to _idle() (bsc#1012628).
- scftorture: Forgive memory-allocation failure if KASAN
  (bsc#1012628).
- platform/chrome: cros_ec_lpc: Remove EC panic shutdown timeout
  (bsc#1012628).
- x86/amd_nb: Add PCI IDs for AMD Family 1Ah-based models
  (bsc#1012628).
- perf/smmuv3: Enable HiSilicon Erratum 162001900 quirk for
  HIP08/09 (bsc#1012628).
- s390/boot: cleanup number of page table levels setup
  (bsc#1012628).
- kselftest/arm64: fix a memleak in zt_regs_run() (bsc#1012628).
- perf/imx_ddr: speed up overflow frequency of cycle
  (bsc#1012628).
- ACPI: video: Add backlight=native DMI quirk for Apple iMac12,1
  and iMac12,2 (bsc#1012628).
- hw_breakpoint: fix single-stepping when using
  bpf_overflow_handler (bsc#1012628).
- ACPI: x86: s2idle: Catch multiple ACPI_TYPE_PACKAGE objects
  (bsc#1012628).
- selftests/nolibc: fix up kernel parameters support
  (bsc#1012628).
- selftests/nolibc: prevent out of bounds access in
  expect_vfprintf (bsc#1012628).
- spi: sun6i: add quirk for dual and quad SPI modes support
  (bsc#1012628).
- devlink: remove reload failed checks in params get/set callbacks
  (bsc#1012628).
- crypto: lrw,xts - Replace strlcpy with strscpy (bsc#1012628).
- ice: Don't tx before switchdev is fully configured
  (bsc#1012628).
- wifi: ath9k: fix fortify warnings (bsc#1012628).
- wifi: ath9k: fix printk specifier (bsc#1012628).
- wifi: rtw88: delete timer and free skb queue when unloading
  (bsc#1012628).
- wifi: mwifiex: fix fortify warning (bsc#1012628).
- mt76: mt7921: don't assume adequate headroom for SDIO headers
  (bsc#1012628).
- wifi: wil6210: fix fortify warnings (bsc#1012628).
- can: sun4i_can: Add acceptance register quirk (bsc#1012628).
- can: sun4i_can: Add support for the Allwinner D1 (bsc#1012628).
- net: Use sockaddr_storage for getsockopt(SO_PEERNAME)
  (bsc#1012628).
- wifi: ath12k: Fix a NULL pointer dereference in
  ath12k_mac_op_hw_scan() (bsc#1012628).
- wifi: ath12k: avoid array overflow of hw mode for
  preferred_hw_mode (bsc#1012628).
- net/ipv4: return the real errno instead of -EINVAL
  (bsc#1012628).
- crypto: lib/mpi - avoid null pointer deref in mpi_cmp_ui()
  (bsc#1012628).
- Bluetooth: btusb: Add device 0489:e0f5 as MT7922 device
  (bsc#1012628).
- Bluetooth: btusb: Add a new VID/PID 0489/e0f6 for MT7922
  (bsc#1012628).
- Bluetooth: btusb: Add new VID/PID 0489/e102 for MT7922
  (bsc#1012628).
- Bluetooth: btusb: Add new VID/PID 04ca/3804 for MT7922
  (bsc#1012628).
- Bluetooth: Fix hci_suspend_sync crash (bsc#1012628).
- Bluetooth: btusb: Add support for another MediaTek 7922 VID/PID
  (bsc#1012628).
- netlink: convert nlk->flags to atomic flags (bsc#1012628).
- tpm_tis: Resend command to recover from data transfer errors
  (bsc#1012628).
- mmc: sdhci-esdhc-imx: improve ESDHC_FLAG_ERR010450
  (bsc#1012628).
- alx: fix OOB-read compiler warning (bsc#1012628).
- wifi: iwlwifi: pcie: avoid a warning in case prepare card failed
  (bsc#1012628).
- wifi: mac80211: check S1G action frame size (bsc#1012628).
- netfilter: ebtables: fix fortify warnings in size_entry_mwt()
  (bsc#1012628).
- wifi: cfg80211: reject auth/assoc to AP with our address
  (bsc#1012628).
- wifi: cfg80211: ocb: don't leave if not joined (bsc#1012628).
- wifi: mac80211: check for station first in client probe
  (bsc#1012628).
- wifi: mac80211_hwsim: drop short frames (bsc#1012628).
- Revert "wifi: mac80211_hwsim: check the return value of
  nla_put_u32" (bsc#1012628).
- libbpf: Free btf_vmlinux when closing bpf_object (bsc#1012628).
- wifi: ath12k: Fix memory leak in rx_desc and tx_desc
  (bsc#1012628).
- wifi: ath12k: add check max message length while scanning with
  extraie (bsc#1012628).
- Fix nomenclature for USB and PCI wireless devices (bsc#1012628).
- bpf: Consider non-owning refs trusted (bsc#1012628).
- bpf: Consider non-owning refs to refcounted nodes RCU protected
  (bsc#1012628).
- drm/bridge: tc358762: Instruct DSI host to generate HSE packets
  (bsc#1012628).
- drm/edid: Add quirk for OSVR HDK 2.0 (bsc#1012628).
- drm: bridge: samsung-dsim: Drain command transfer FIFO before
  transfer (bsc#1012628).
- arm64: dts: qcom: sm6125-pdx201: correct ramoops pmsg-size
  (bsc#1012628).
- arm64: dts: qcom: sm6125-sprout: correct ramoops pmsg-size
  (bsc#1012628).
- arm64: dts: qcom: sm6350: correct ramoops pmsg-size
  (bsc#1012628).
- arm64: dts: qcom: sm8150-kumano: correct ramoops pmsg-size
  (bsc#1012628).
- arm64: dts: qcom: sm8250-edo: correct ramoops pmsg-size
  (bsc#1012628).
- drm/amdgpu: Increase soft IH ring size (bsc#1012628).
- samples/hw_breakpoint: Fix kernel BUG 'invalid opcode: 0000'
  (bsc#1012628).
- drm/amdgpu: Update ring scheduler info as needed (bsc#1012628).
- drm/amd/display: Fix underflow issue on 175hz timing
  (bsc#1012628).
- ASoC: SOF: topology: simplify code to prevent static analysis
  warnings (bsc#1012628).
- ASoC: Intel: sof_sdw: Update BT offload config for soundwire
  config (bsc#1012628).
- ALSA: hda: intel-dsp-cfg: add LunarLake support (bsc#1012628).
- drm/amd/display: Use DTBCLK as refclk instead of DPREFCLK
  (bsc#1012628).
- drm/amd/display: Blocking invalid 420 modes on HDMI TMDS for
  DCN31 (bsc#1012628).
- drm/amd/display: Blocking invalid 420 modes on HDMI TMDS for
  DCN314 (bsc#1012628).
- drm/amd/display: Use max memclk variable when setting max memclk
  (bsc#1012628).
- drm/msm/adreno: Use quirk identify hw_apriv (bsc#1012628).
- drm/msm/adreno: Use quirk to identify cached-coherent support
  (bsc#1012628).
- drm/exynos: fix a possible null-pointer dereference due to
  data race in exynos_drm_crtc_atomic_disable() (bsc#1012628).
- io_uring: annotate the struct io_kiocb slab for appropriate
  user copy (bsc#1012628).
- drm/mediatek: dp: Change logging to dev for
  mtk_dp_aux_transfer() (bsc#1012628).
- bus: ti-sysc: Configure uart quirks for k3 SoC (bsc#1012628).
- arm64: dts: qcom: sc8280xp-x13s: Add camera activity LED
  (bsc#1012628).
- md: raid1: fix potential OOB in raid1_remove_disk()
  (bsc#1012628).
- ext2: fix datatype of block number in ext2_xattr_set2()
  (bsc#1012628).
- blk-mq: fix tags leak when shrink nr_hw_queues (bsc#1012628).
- ASoC: SOF: amd: clear panic mask status when panic occurs
  (bsc#1012628).
- x86: bring back rep movsq for user access on CPUs without ERMS
  (bsc#1012628).
- fs/jfs: prevent double-free in dbUnmount() after failed
  jfs_remount() (bsc#1012628).
- jfs: fix invalid free of JFS_IP(ipimap)->i_imap in diUnmount
  (bsc#1012628).
- ext4: add two helper functions extent_logical_end() and
  pa_logical_end() (bsc#1012628).
- ext4: avoid overlapping preallocations due to overflow
  (bsc#1012628).
- PCI: dwc: Provide deinit callback for i.MX (bsc#1012628).
- ARM: 9317/1: kexec: Make smp stop calls asynchronous
  (bsc#1012628).
- powerpc/pseries: fix possible memory leak in ibmebus_bus_init()
  (bsc#1012628).
- PCI: vmd: Disable bridge window for domain reset (bsc#1012628).
- PCI: fu740: Set the number of MSI vectors (bsc#1012628).
- media: mdp3: Fix resource leaks in of_find_device_by_node
  (bsc#1012628).
- media: dvb-usb-v2: af9035: Fix null-ptr-deref in
  af9035_i2c_master_xfer (bsc#1012628).
- media: dw2102: Fix null-ptr-deref in dw2102_i2c_transfer()
  (bsc#1012628).
- media: af9005: Fix null-ptr-deref in af9005_i2c_xfer
  (bsc#1012628).
- media: anysee: fix null-ptr-deref in anysee_master_xfer
  (bsc#1012628).
- media: az6007: Fix null-ptr-deref in az6007_i2c_xfer()
  (bsc#1012628).
- media: dvb-usb-v2: gl861: Fix null-ptr-deref in
  gl861_i2c_master_xfer (bsc#1012628).
- scsi: lpfc: Abort outstanding ELS cmds when mailbox timeout
  error is detected (bsc#1012628).
- media: tuners: qt1010: replace BUG_ON with a regular error
  (bsc#1012628).
- media: pci: cx23885: replace BUG with error return
  (bsc#1012628).
- usb: cdns3: Put the cdns set active part outside the spin lock
  (bsc#1012628).
- usb: typec: intel_pmc_mux: Add new ACPI ID for Lunar Lake IOM
  device (bsc#1012628).
- usb: gadget: fsl_qe_udc: validate endpoint index for ch9 udc
  (bsc#1012628).
- tools: iio: iio_generic_buffer: Fix some integer type and
  calculation (bsc#1012628).
- scsi: target: iscsi: Fix buffer overflow in
  lio_target_nacl_info_show() (bsc#1012628).
- serial: cpm_uart: Avoid suspicious locking (bsc#1012628).
- misc: open-dice: make OPEN_DICE depend on HAS_IOMEM
  (bsc#1012628).
- usb: dwc3: dwc3-octeon: Verify clock divider (bsc#1012628).
- usb: ehci: add workaround for chipidea PORTSC.PEC bug
  (bsc#1012628).
- usb: chipidea: add workaround for chipidea PEC bug
  (bsc#1012628).
- media: pci: ipu3-cio2: Initialise timing struct to avoid a
  compiler warning (bsc#1012628).
- kobject: Add sanity check for kset->kobj.ktype in
  kset_register() (bsc#1012628).
- interconnect: Fix locking for runpm vs reclaim (bsc#1012628).
- usb: typec: qcom-pmic-typec: register drm_bridge (bsc#1012628).
- printk: Reduce console_unblank() usage in unsafe scenarios
  (bsc#1012628).
- printk: Keep non-panic-CPUs out of console lock (bsc#1012628).
- printk: Do not take console lock for console_flush_on_panic()
  (bsc#1012628).
- printk: Consolidate console deferred printing (bsc#1012628).
- printk: Rename abandon_console_lock_in_panic() to
  other_cpu_in_panic() (bsc#1012628).
- ext4: fix BUG in ext4_mb_new_inode_pa() due to overflow
  (bsc#1012628).
- btrfs: introduce struct to consolidate extent buffer write
  context (bsc#1012628).
- btrfs: zoned: introduce block group context to
  btrfs_eb_write_context (bsc#1012628).
- btrfs: zoned: return int from btrfs_check_meta_write_pointer
  (bsc#1012628).
- btrfs: zoned: defer advancing meta write pointer (bsc#1012628).
- btrfs: zoned: activate metadata block group on write time
  (bsc#1012628).
- mtd: spi-nor: spansion: use CLPEF as an alternative to CLSR
  (bsc#1012628).
- mtd: spi-nor: spansion: preserve CFR2V[7] when writing MEMLAT
  (bsc#1012628).
- btrfs: add a helper to read the superblock metadata_uuid
  (bsc#1012628).
- btrfs: compare the correct fsid/metadata_uuid in
  btrfs_validate_super (bsc#1012628).
- nvmet-tcp: pass iov_len instead of sg->length to bvec_set_page()
  (bsc#1012628).
- drm: gm12u320: Fix the timeout usage for usb_bulk_msg()
  (bsc#1012628).
- scsi: qla2xxx: Fix NULL vs IS_ERR() bug for debugfs_create_dir()
  (bsc#1012628).
- md: don't dereference mddev after export_rdev() (bsc#1012628).
- md: fix warning for holder mismatch from export_rdev()
  (bsc#1012628).
- PM: hibernate: Fix the exclusive get block device in test_resume
  mode (bsc#1012628).
- selftests: tracing: Fix to unmount tracefs for recovering
  environment (bsc#1012628).
- x86/ibt: Suppress spurious ENDBR (bsc#1012628).
- x86/ibt: Avoid duplicate ENDBR in __put_user_nocheck*()
  (bsc#1012628).
- riscv: kexec: Align the kexeced kernel entry (bsc#1012628).
- x86/sched: Restore the SD_ASYM_PACKING flag in the DIE domain
  (bsc#1012628).
- scsi: target: core: Fix target_cmd_counter leak (bsc#1012628).
- scsi: lpfc: Fix the NULL vs IS_ERR() bug for
  debugfs_create_file() (bsc#1012628).
- panic: Reenable preemption in WARN slowpath (bsc#1012628).
- ata: libata-core: fetch sense data for successful commands
  iff CDL enabled (bsc#1012628).
- x86/boot/compressed: Reserve more memory for page tables
  (bsc#1012628).
- x86/purgatory: Remove LTO flags (bsc#1012628).
- samples/hw_breakpoint: fix building without module unloading
  (bsc#1012628).
- blk-mq: prealloc tags when increase tagset nr_hw_queues
  (bsc#1012628).
- blk-mq: fix tags UAF when shrinking q->nr_hw_queues
  (bsc#1012628).
- md/raid1: fix error: ISO C90 forbids mixed declarations
  (bsc#1012628).
- Revert "SUNRPC: Fail faster on bad verifier" (bsc#1012628).
- attr: block mode changes of symlinks (bsc#1012628).
- ovl: fix failed copyup of fileattr on a symlink (bsc#1012628).
- ovl: fix incorrect fdput() on aio completion (bsc#1012628).
- io_uring/net: fix iter retargeting for selected buf
  (bsc#1012628).
- nvme: avoid bogus CRTO values (bsc#1012628).
- x86/platform/uv: Use alternate source for socket to node data
  (bsc#1012628).
- Revert "firewire: core: obsolete usage of GFP_ATOMIC at building
  node tree" (bsc#1012628).
- md: Put the right device in md_seq_next (bsc#1012628).
- drm/amd: Make fence wait in suballocator uninterruptible
  (bsc#1012628).
- Revert "drm/amd: Disable S/G for APUs when 64GB or more host
  memory" (bsc#1012628).
- dm: don't attempt to queue IO under RCU protection
  (bsc#1012628).
- dm: fix a race condition in retrieve_deps (bsc#1012628).
- btrfs: fix lockdep splat and potential deadlock after failure
  running delayed items (bsc#1012628).
- btrfs: fix a compilation error if DEBUG is defined in
  btree_dirty_folio (bsc#1012628).
- btrfs: fix race between finishing block group creation and
  its item update (bsc#1012628).
- btrfs: release path before inode lookup during the ino lookup
  ioctl (bsc#1012628).
- btrfs: check for BTRFS_FS_ERROR in pending ordered assert
  (bsc#1012628).
- tracing/synthetic: Fix order of struct trace_dynamic_info
  (bsc#1012628).
- tracing: Have tracing_max_latency inc the trace array ref count
  (bsc#1012628).
- tracing: Have event inject files inc the trace array ref count
  (bsc#1012628).
- tracing/synthetic: Print out u64 values properly (bsc#1012628).
- tracing: Increase trace array ref count on enable and filter
  files (bsc#1012628).
- tracing: Have current_trace inc the trace array ref count
  (bsc#1012628).
- tracing: Have option files inc the trace array ref count
  (bsc#1012628).
- selinux: fix handling of empty opts in
  selinux_fs_context_submount() (bsc#1012628).
- nfsd: fix change_info in NFSv4 RENAME replies (bsc#1012628).
- tracefs: Add missing lockdown check to tracefs_create_dir()
  (bsc#1012628).
- i2c: aspeed: Reset the i2c controller when timeout occurs
  (bsc#1012628).
- ata: libata: disallow dev-initiated LPM transitions to
  unsupported states (bsc#1012628).
- ata: libahci: clear pending interrupt status (bsc#1012628).
- scsi: megaraid_sas: Fix deadlock on firmware crashdump
  (bsc#1012628).
- scsi: qla2xxx: Use raw_smp_processor_id() instead of
  smp_processor_id() (bsc#1012628).
- scsi: pm8001: Setup IRQs on resume (bsc#1012628).
- Revert "comedi: add HAS_IOPORT dependencies" (bsc#1012628).
- ext4: fix rec_len verify error (bsc#1012628).
- drm/radeon: make fence wait in suballocator uninterrruptable
  (bsc#1012628).
- drm/i915: Only check eDP HPD when AUX CH is shared
  (bsc#1012628).
- drm/amdkfd: Insert missing TLB flush on GFX10 and later
  (bsc#1012628).
- drm/tests: helpers: Avoid a driver uaf (bsc#1012628).
- drm/amd/display: Adjust the MST resume flow (bsc#1012628).
- drm/amd/display: fix the white screen issue when >= 64GB DRAM
  (bsc#1012628).
- drm/amd/display: Add DPIA Link Encoder Assignment Fix
  (bsc#1012628).
- drm/amd/display: Fix 2nd DPIA encoder Assignment (bsc#1012628).
- Revert "memcg: drop kmem.limit_in_bytes" (bsc#1012628).
- drm/amdgpu: fix amdgpu_cs_p1_user_fence (bsc#1012628).
- interconnect: Teach lockdep about icc_bw_lock order
  (bsc#1012628).
- x86/alternatives: Remove faulty optimization (bsc#1012628).
- x86,static_call: Fix static-call vs return-thunk (bsc#1012628).
- Update config files.
  * restore COMEDI_ISA_DRIVERS=n
  * CAN_SUN4I=m, following master
- Rename to
  patches.kernel.org/6.5.5-010-ACPI-video-Add-backlight-native-DMI-quirk-for-L.patch.
- Rename to
  patches.kernel.org/6.5.5-147-efivarfs-fix-statfs-on-efivarfs.patch.