git_sort: Check if Patch-mainline tag exists
If Patch-mainline and Git-commit tags are missing in the patch, sort script
will fail with:

    IndexError: list index out of range

This change ensures that Patch-mainline tag is present and if not, raise
an error to warn the user.

Signed-off-by: Alexandre Vicenzi <alexandre.vicenzi@suse.com>